<wsdl:definitions
     name="pollFile"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/ftp/Proj-Fusion/CDRProcessor/pollFile"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/Proj-Fusion/CDRProcessor/pollFile"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:imp1="http://TargetNamespace.com/pollFile"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
    >
  <plt:partnerLinkType name="Get_plt" >
    <plt:role name="Get_role" >
      <plt:portType name="tns:Get_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://TargetNamespace.com/pollFile" schemaLocation="xsd/cdr.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="Get_msg">
        <wsdl:part name="body" element="imp1:cdrs"/>
    </wsdl:message>
    <wsdl:portType name="Get_ptt">
        <wsdl:operation name="Get">
            <wsdl:input message="tns:Get_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
